### PR TITLE
add gitattributes

### PR DESCRIPTION
**Pull request by orrblue**
This will collapse irrelevant files during pull request reviews -- when we review the diffs. Files such as meta files will be collapsed so they don't clutter the screen.

### CODE REVIEW

**Comment by erwang01** [comment]
wait so does this only work for PRs or our local command line as well?

if its PR only I think this is good. If its command line as well is there a way to override it?

Edit: Looks like command line still shows diff.
image

**Review by erwang01 — APPROVED** [review]
Not sure if I'm exactly at liberty to approve this but looks alright to me.

Might be worth adding is ignoring Windows Line endings:
https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings#per-repository-settings

**Comment by erwang01** [comment]
Please open up a git issue if we don't end up adding the line ending attributes. Thanks.

**Review by exofunctor — COMMENTED** [review]
We should include .fbx (meshes) and .blend (Blender). Also, I think .meta might be a better candidate for .gitignore, as they are system dependent, and automatically generated by Unity (there's no need we ship them with the repository).

**Comment by exofunctor** [comment]
Also agreed with @erwang01 proposal above.

**Comment by exofunctor** [comment]
@orrblue @erwang01  let me know what you think about .meta files, otherwise I'm good with merging.

**Review by erwang01 — CHANGES_REQUESTED** [review]
see comments above.

**Comment by erwang01** [comment]
@apollovision .meta is specifically not ignored within the Unity.gitignore. not sure why...

**Comment by orrblue** [comment]
I think line endings aren't causing us problems. Looks like windows clients are doing fine. So let's leave this as is for now, and merge?

As for adding .meta files and other file types, those would go into the .gitignore file rather than this .gitattributes file. However, I read that .meta should not be added to .gitignore

Please approve this PR and merge if all's good

**Comment by erwang01** [comment]
So I pulled in the Unity gitattributes template. there has been significant additions if someone wants to review them.

**Review by exofunctor — APPROVED** [review]
It seems good to me. I'll search the .meta issue more just in case, but for now feel free to merge.

**Review by exofunctor — APPROVED** [review]

**Review by erwang01 — APPROVED** [review]

**Pull request merged**
