### PR TITLE
Fix ROSBridgeLib Submodule Reference

### PR DESCRIPTION
**Pull request by erwang01**
Made ROSBridgeLib into a Submodule.

### CODE REVIEW

**Comment by orrblue** [comment]
What was it before @erwang01 ?

**Comment by erwang01** [comment]
It was migrated into this new repo as individual files. See commit [e570f52](https://github.com/immersive-command-system/ImmersiveDroneInterface_2/pull/39/commits/e570f520994b1b545426518405230f0a327f9db9) for the files I removed.

**Comment by exofunctor** [comment]
Does that mean we can now use a simpler command to initiate the submodules? (Instead of what's outlined in: https://github.com/immersive-command-system/ImmersiveDroneInterface)

**Comment by erwang01** [comment]
well you use `git submodule update --init --recursive`

(Even ImmersiveDroneInterface uses that in RadVizIntegration branch). It was just during the migration over to ImmersiveDroneInterface_2, we lost the submodule reference and git thought ROSBridgeLib was part of this repo rather than a submodule.

**Review by orrblue — CHANGES_REQUESTED** [review]
Looks pretty good, can you just add these git submodule instruction to the readme before we merge this. Link to instructions from our old repo: https://github.com/immersive-command-system/ImmersiveDroneInterface#setup

**Comment by erwang01** [comment]
Fixed. Also we should probably update the README to be less cluttered in the future. Maybe break into multiple pages / move some to the wiki?

**Comment by erwang01** [comment]
image
seems to work fine. Do need to be careful about having a SSH key tho.

**Review by orrblue — APPROVED** [review]
Looks good! Thank you

**Pull request merged**
